// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dv_import.proto

package dv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BandwidthStatistics struct {
	// all devices that join this server instance
	// will be reported, even it's flow is zero.
	// the controller server can know that which
	// devices are attached to this DV server now.
	Statistics           []*BandwidthUsage `protobuf:"bytes,1,rep,name=statistics,proto3" json:"statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BandwidthStatistics) Reset()         { *m = BandwidthStatistics{} }
func (m *BandwidthStatistics) String() string { return proto.CompactTextString(m) }
func (*BandwidthStatistics) ProtoMessage()    {}
func (*BandwidthStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_134b56f6ca400117, []int{0}
}

func (m *BandwidthStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BandwidthStatistics.Unmarshal(m, b)
}
func (m *BandwidthStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BandwidthStatistics.Marshal(b, m, deterministic)
}
func (m *BandwidthStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BandwidthStatistics.Merge(m, src)
}
func (m *BandwidthStatistics) XXX_Size() int {
	return xxx_messageInfo_BandwidthStatistics.Size(m)
}
func (m *BandwidthStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_BandwidthStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_BandwidthStatistics proto.InternalMessageInfo

func (m *BandwidthStatistics) GetStatistics() []*BandwidthUsage {
	if m != nil {
		return m.Statistics
	}
	return nil
}

type BandwidthUsage struct {
	// device uuid
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// total sent bytes in this report period
	SendBytes uint64 `protobuf:"varint,2,opt,name=send_bytes,json=sendBytes,proto3" json:"send_bytes,omitempty"`
	// total recv_bytes in this report period
	RecvBytes            uint64   `protobuf:"varint,3,opt,name=recv_bytes,json=recvBytes,proto3" json:"recv_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BandwidthUsage) Reset()         { *m = BandwidthUsage{} }
func (m *BandwidthUsage) String() string { return proto.CompactTextString(m) }
func (*BandwidthUsage) ProtoMessage()    {}
func (*BandwidthUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_134b56f6ca400117, []int{1}
}

func (m *BandwidthUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BandwidthUsage.Unmarshal(m, b)
}
func (m *BandwidthUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BandwidthUsage.Marshal(b, m, deterministic)
}
func (m *BandwidthUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BandwidthUsage.Merge(m, src)
}
func (m *BandwidthUsage) XXX_Size() int {
	return xxx_messageInfo_BandwidthUsage.Size(m)
}
func (m *BandwidthUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_BandwidthUsage.DiscardUnknown(m)
}

var xxx_messageInfo_BandwidthUsage proto.InternalMessageInfo

func (m *BandwidthUsage) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BandwidthUsage) GetSendBytes() uint64 {
	if m != nil {
		return m.SendBytes
	}
	return 0
}

func (m *BandwidthUsage) GetRecvBytes() uint64 {
	if m != nil {
		return m.RecvBytes
	}
	return 0
}

type ReportResult struct {
	// should always be 0
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportResult) Reset()         { *m = ReportResult{} }
func (m *ReportResult) String() string { return proto.CompactTextString(m) }
func (*ReportResult) ProtoMessage()    {}
func (*ReportResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_134b56f6ca400117, []int{2}
}

func (m *ReportResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResult.Unmarshal(m, b)
}
func (m *ReportResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResult.Marshal(b, m, deterministic)
}
func (m *ReportResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResult.Merge(m, src)
}
func (m *ReportResult) XXX_Size() int {
	return xxx_messageInfo_ReportResult.Size(m)
}
func (m *ReportResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResult proto.InternalMessageInfo

func (m *ReportResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type CfgPullRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CfgPullRequest) Reset()         { *m = CfgPullRequest{} }
func (m *CfgPullRequest) String() string { return proto.CompactTextString(m) }
func (*CfgPullRequest) ProtoMessage()    {}
func (*CfgPullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_134b56f6ca400117, []int{3}
}

func (m *CfgPullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CfgPullRequest.Unmarshal(m, b)
}
func (m *CfgPullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CfgPullRequest.Marshal(b, m, deterministic)
}
func (m *CfgPullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CfgPullRequest.Merge(m, src)
}
func (m *CfgPullRequest) XXX_Size() int {
	return xxx_messageInfo_CfgPullRequest.Size(m)
}
func (m *CfgPullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CfgPullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CfgPullRequest proto.InternalMessageInfo

func (m *CfgPullRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type CfgPullResult struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	BandwidthLimitKbs    uint64   `protobuf:"varint,2,opt,name=bandwidth_limit_kbs,json=bandwidthLimitKbs,proto3" json:"bandwidth_limit_kbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CfgPullResult) Reset()         { *m = CfgPullResult{} }
func (m *CfgPullResult) String() string { return proto.CompactTextString(m) }
func (*CfgPullResult) ProtoMessage()    {}
func (*CfgPullResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_134b56f6ca400117, []int{4}
}

func (m *CfgPullResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CfgPullResult.Unmarshal(m, b)
}
func (m *CfgPullResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CfgPullResult.Marshal(b, m, deterministic)
}
func (m *CfgPullResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CfgPullResult.Merge(m, src)
}
func (m *CfgPullResult) XXX_Size() int {
	return xxx_messageInfo_CfgPullResult.Size(m)
}
func (m *CfgPullResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CfgPullResult.DiscardUnknown(m)
}

var xxx_messageInfo_CfgPullResult proto.InternalMessageInfo

func (m *CfgPullResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CfgPullResult) GetBandwidthLimitKbs() uint64 {
	if m != nil {
		return m.BandwidthLimitKbs
	}
	return 0
}

func init() {
	proto.RegisterType((*BandwidthStatistics)(nil), "BandwidthStatistics")
	proto.RegisterType((*BandwidthUsage)(nil), "BandwidthUsage")
	proto.RegisterType((*ReportResult)(nil), "ReportResult")
	proto.RegisterType((*CfgPullRequest)(nil), "CfgPullRequest")
	proto.RegisterType((*CfgPullResult)(nil), "CfgPullResult")
}

func init() { proto.RegisterFile("dv_import.proto", fileDescriptor_134b56f6ca400117) }

var fileDescriptor_134b56f6ca400117 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4b, 0xfb, 0x30,
	0x14, 0xc7, 0xd7, 0xdf, 0xf6, 0x9b, 0xec, 0xe9, 0x56, 0xcc, 0x3c, 0x94, 0x81, 0x50, 0x82, 0x87,
	0x1e, 0x24, 0x83, 0x7a, 0xf6, 0xd2, 0x89, 0x17, 0x3d, 0x48, 0x86, 0xe7, 0xd2, 0x34, 0x6f, 0x35,
	0xd8, 0xad, 0xb3, 0x49, 0x2b, 0xfe, 0xf7, 0x92, 0xae, 0x2b, 0x2b, 0xcc, 0x53, 0x5e, 0xde, 0xe7,
	0x4b, 0xde, 0xf7, 0xfb, 0x02, 0xae, 0xac, 0x63, 0xb5, 0xdd, 0x17, 0xa5, 0x61, 0xfb, 0xb2, 0x30,
	0x05, 0x7d, 0x86, 0x79, 0x94, 0xec, 0xe4, 0xb7, 0x92, 0xe6, 0x63, 0x6d, 0x12, 0xa3, 0xb4, 0x51,
	0xa9, 0x26, 0x4b, 0x00, 0xdd, 0xdd, 0x3c, 0xc7, 0x1f, 0x06, 0x97, 0xa1, 0xcb, 0x3a, 0xe5, 0xbb,
	0x4e, 0x32, 0xe4, 0x27, 0x12, 0x2a, 0x60, 0xd6, 0xa7, 0x84, 0xc0, 0xa8, 0xaa, 0x94, 0xf4, 0x1c,
	0xdf, 0x09, 0x26, 0xbc, 0xa9, 0xc9, 0x2d, 0x80, 0xc6, 0x9d, 0x8c, 0xc5, 0x8f, 0x41, 0xed, 0xfd,
	0xf3, 0x9d, 0x60, 0xc4, 0x27, 0xb6, 0x13, 0xd9, 0x86, 0xc5, 0x25, 0xa6, 0x75, 0x8b, 0x87, 0x07,
	0x6c, 0x3b, 0x0d, 0xa6, 0x14, 0xae, 0x38, 0x5a, 0xef, 0x1c, 0x75, 0x95, 0x1b, 0x3b, 0x21, 0x2d,
	0x24, 0x36, 0x13, 0xfe, 0xf3, 0xa6, 0xa6, 0x77, 0x30, 0x5b, 0x6d, 0xb2, 0xb7, 0x2a, 0xcf, 0x39,
	0x7e, 0x55, 0xa8, 0xcd, 0x39, 0x1f, 0x74, 0x0d, 0xd3, 0x4e, 0xf5, 0xd7, 0x53, 0x84, 0xc1, 0x5c,
	0x1c, 0x23, 0xc5, 0xb9, 0xda, 0x2a, 0x13, 0x7f, 0x8a, 0xa3, 0xeb, 0xeb, 0x0e, 0xbd, 0x5a, 0xf2,
	0x22, 0x74, 0x18, 0x81, 0xdb, 0xad, 0xe0, 0xe0, 0x93, 0x2c, 0x61, 0xdc, 0x56, 0x37, 0xec, 0xcc,
	0x9a, 0x17, 0x53, 0x76, 0x1a, 0x88, 0x0e, 0xc2, 0x47, 0x98, 0x3e, 0x61, 0xad, 0x52, 0x6c, 0xed,
	0x91, 0x7b, 0xb8, 0xb0, 0xe7, 0x6a, 0x93, 0x11, 0x97, 0xf5, 0x93, 0x2d, 0x66, 0xac, 0x17, 0x82,
	0x0e, 0xc4, 0xb8, 0xf9, 0xd4, 0x87, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xe5, 0xde, 0xbf,
	0xe7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BandwidthReportClient is the client API for BandwidthReport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BandwidthReportClient interface {
	Report(ctx context.Context, in *BandwidthStatistics, opts ...grpc.CallOption) (*ReportResult, error)
}

type bandwidthReportClient struct {
	cc *grpc.ClientConn
}

func NewBandwidthReportClient(cc *grpc.ClientConn) BandwidthReportClient {
	return &bandwidthReportClient{cc}
}

func (c *bandwidthReportClient) Report(ctx context.Context, in *BandwidthStatistics, opts ...grpc.CallOption) (*ReportResult, error) {
	out := new(ReportResult)
	err := c.cc.Invoke(ctx, "/BandwidthReport/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BandwidthReportServer is the server API for BandwidthReport service.
type BandwidthReportServer interface {
	Report(context.Context, *BandwidthStatistics) (*ReportResult, error)
}

// UnimplementedBandwidthReportServer can be embedded to have forward compatible implementations.
type UnimplementedBandwidthReportServer struct {
}

func (*UnimplementedBandwidthReportServer) Report(ctx context.Context, req *BandwidthStatistics) (*ReportResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}

func RegisterBandwidthReportServer(s *grpc.Server, srv BandwidthReportServer) {
	s.RegisterService(&_BandwidthReport_serviceDesc, srv)
}

func _BandwidthReport_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BandwidthStatistics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BandwidthReportServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BandwidthReport/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BandwidthReportServer).Report(ctx, req.(*BandwidthStatistics))
	}
	return interceptor(ctx, in, info, handler)
}

var _BandwidthReport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BandwidthReport",
	HandlerType: (*BandwidthReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _BandwidthReport_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dv_import.proto",
}

// DeviceCfgPullClient is the client API for DeviceCfgPull service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceCfgPullClient interface {
	PullCfg(ctx context.Context, in *CfgPullRequest, opts ...grpc.CallOption) (*CfgPullResult, error)
}

type deviceCfgPullClient struct {
	cc *grpc.ClientConn
}

func NewDeviceCfgPullClient(cc *grpc.ClientConn) DeviceCfgPullClient {
	return &deviceCfgPullClient{cc}
}

func (c *deviceCfgPullClient) PullCfg(ctx context.Context, in *CfgPullRequest, opts ...grpc.CallOption) (*CfgPullResult, error) {
	out := new(CfgPullResult)
	err := c.cc.Invoke(ctx, "/DeviceCfgPull/PullCfg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceCfgPullServer is the server API for DeviceCfgPull service.
type DeviceCfgPullServer interface {
	PullCfg(context.Context, *CfgPullRequest) (*CfgPullResult, error)
}

// UnimplementedDeviceCfgPullServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceCfgPullServer struct {
}

func (*UnimplementedDeviceCfgPullServer) PullCfg(ctx context.Context, req *CfgPullRequest) (*CfgPullResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullCfg not implemented")
}

func RegisterDeviceCfgPullServer(s *grpc.Server, srv DeviceCfgPullServer) {
	s.RegisterService(&_DeviceCfgPull_serviceDesc, srv)
}

func _DeviceCfgPull_PullCfg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CfgPullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceCfgPullServer).PullCfg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DeviceCfgPull/PullCfg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceCfgPullServer).PullCfg(ctx, req.(*CfgPullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceCfgPull_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DeviceCfgPull",
	HandlerType: (*DeviceCfgPullServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullCfg",
			Handler:    _DeviceCfgPull_PullCfg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dv_import.proto",
}
